Repository pJanks/jeopardy, pull requests merged in 2019-12, with the labels that each got.

#6 Building classes
  data/dataset.js
  src/Clue.js
  src/Game.js
  src/Player.js
  src/Round.js
  src/index.js
  test/Clue-test.js
Labels: enhancement

#7 Build basic html and styling
  package-lock.json
  src/css/base.scss
  src/images/baby_yoda.png
  src/images/space_background_2.jpg
  src/index.html
  src/index.js
  src/main.js
Labels: enhancement

#11 Refactor js to jquery
  src/main.js
Labels: documentation

#13 Minor fixes
  src/Player.js
  src/Round.js
  src/css/base.scss
  src/domUpdates.js
  src/index.js
  src/main.js
Labels: documentation

#15 New instantiations Update DOM with categories
  README.md
  src/Game.js
  src/css/base.scss
  src/domUpdates.js
  src/images/turing-logo.png
  src/index.html
Labels: documentation, enhancement

#19 Create all three necessary rounds
  src/domUpdates.js
Labels: enhancement

#20 Instantiate clues
  src/Game.js
  src/domUpdates.js
Labels: enhancement, question

#26 Refactoring methods
  src/Game.js
  src/domUpdates.js
  src/index.js
Labels: enhancement

#32 Catch bugs
  src/Game.js
  src/index.js
Labels: dependencies, enhancement

#34 Getting specific questions
  src/domUpdates.js
Labels: enhancement

#37 Incorporate correct/incorrect answer screen
  src/domUpdates.js
  src/index.html
Labels: enhancement

#38 Answer evaluation part 2
  src/Clue.js
  src/domUpdates.js
Labels: enhancement
